# Generated by Django 4.2.30 on 2026-09-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('verdict', models.CharField(max_length=20)),
                ('confidence', models.FloatField()),
                ('risk_score', models.FloatField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('features', models.JSONField(default=dict)),
                ('explanations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
